### ISSUE TITLE
Multiple destination support

### ISSUE THREAD

**Issue by ktquez** [vue-a11y/vue-skip-to#1]
# v2.0
- Multiple destination support by dropdown menu

e.g.:
- Skip to link
![group 1](https://user-images.githubusercontent.com/8084606/40147800-7da9c9ee-5941-11e8-9d9c-7adf688bc9b9.png)

- Dropdown menu com multiples destination
![group 2](https://user-images.githubusercontent.com/8084606/40147846-a7692aa4-5941-11e8-989c-adccaa9b3753.png)

**Comment by shwilliam** [comment]
Has any progress been made on this feature yet? Would be happy to help implement support for this!

**Comment by ktquez** [comment]
Hey @shwilliam, how are you?

It would be very helpful to have your contribution on vue-skit-to.

**Comment by shwilliam** [comment]
Great, thanks!

Sweet, will get started on this then 👍
