### ISSUE TITLE
use vue slot syntax

### ISSUE THREAD

**Issue by shwilliam** [vue-a11y/vue-skip-to#2]
As opposed to using a 'text' prop to allow users to change the displayed text, it would be nice to write it as a child of the <vue-skip-to> component. If you would like I can go ahead and make a PR with this functionality implemented using Vue's slot syntax (which has been [recently updated](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0001-new-slot-syntax.md)).

This allows the component to be used as follows with a syntax inspired by the [W3C Web Components spec draft](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Slots-Proposal.md):

```html
<template>
  <div id="app">

    <vue-skip-to to="#main-content">
      Custom skip text
    </vue-skip-to>
    
    [...]

  </div>
</template>
```

**Comment by ktquez** [comment]
Awesome @shwilliam 
We would be grateful for the contribution with a PR

**Comment by ktquez** [comment]
Added in new version [v1.0.6](https://github.com/vue-a11y/vue-skip-to/tree/v1.0.6)
Thanks
