### ISSUE TITLE
tabindex on the skip link?

### ISSUE THREAD

**Issue by scottaohara** [vue-a11y/vue-skip-to#4]
Links with `href`s that aren't an empty string are focusable by default, so I'm curious to the intention of the [`tabindex` on the skip link](https://github.com/vue-a11y/vue-skip-to/blob/master/src/skip-to.vue#L2)?

**Comment by ktquez** [comment]
I believe there was no pretense of some user using tabindex, by default it is never inserted in the link.
I don't encourage its use, in a next update I believe it will be removed, we will use $attrs, eliminating unnecessary props.

**Comment by scottaohara** [comment]
Good to hear. Stuff like that just immediately raises red flags to me, as if provided the option there will be someone to misuse it down the line :)
